import { Data, IProductInput, IUserInput } from '@/types'
import { toSlug } from './utils'
import bcrypt from 'bcryptjs'

const products: IProductInput[] = [
  // Caméras de surveillance
  {
    name: 'Hikvision Dome Camera 4MP IP Security Camera',
    slug: toSlug('Hikvision Dome Camera 4MP IP Security Camera'),
    category: 'Video Surveillance',
    images: ['/images/p11-1.jpg', '/images/p11-2.jpg'],
    tags: ['new-arrival', 'featured', 'todays-deal'],
    isPublished: true,
    price: 89.99,
    listPrice: 129.99,
    brand: 'Hikvision',
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    numSales: 9,
    countInStock: 11,
    description:
      'Caméra de surveillance IP 4MP avec vision nocturne, détection de mouvement et résistance IP67. Parfaite pour la surveillance intérieure et extérieure.',
    specifications: [
      '4MP Resolution',
      'Night Vision',
      'Motion Detection',
      'IP67 Waterproof',
    ],
    compatibility: ['Hikvision NVR', 'Universal ONVIF'],
    colors: ['White', 'Black'],
    reviews: [],
  },
  {
    name: 'Dahua IP Camera 2MP Bullet Security Camera',
    slug: toSlug('Dahua IP Camera 2MP Bullet Security Camera'),
    category: 'Video Surveillance',
    images: [
      '/images/p12-1.jpg',
      '/images/p12-2.jpg',
      '/images/p12-3.jpg',
      '/images/p12-4.jpg',
    ],
    tags: ['featured', 'best-seller'],
    isPublished: true,
    price: 67.99,
    listPrice: 89.99,
    brand: 'Dahua',
    avgRating: 4.2,
    numReviews: 10,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    numSales: 29,
    countInStock: 12,
    description:
      "Caméra de surveillance IP bullet 2MP avec vision nocturne jusqu'à 30m, détection de mouvement intelligente et résistance IP67. Idéale pour la surveillance extérieure.",
    specifications: [
      '2MP Resolution',
      'Night Vision 30m',
      'Smart Motion Detection',
      'IP67 Waterproof',
    ],
    compatibility: ['Dahua NVR', 'Universal ONVIF'],
    colors: ['Black', 'White'],
    reviews: [],
  },
  {
    name: 'Samsung 24" LED Monitor Full HD',
    slug: toSlug('Samsung 24 LED Monitor Full HD'),
    category: 'Computer Equipment',
    brand: 'Samsung',
    images: ['/images/p13-1.jpg', '/images/p13-2.jpg'],
    tags: ['best-seller', 'featured'],
    isPublished: true,
    price: 149.99,
    listPrice: 199.99,
    avgRating: 4,
    numReviews: 12,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 2 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    numSales: 55,
    countInStock: 13,
    description:
      'Moniteur LED Samsung 24 pouces avec résolution Full HD 1920x1080, temps de réponse 5ms et design ultra-fin. Parfait pour le travail, la bureautique et les jeux occasionnels.',
    specifications: [
      '24" Display',
      'Full HD 1920x1080',
      '5ms Response Time',
      'VGA/HDMI Ports',
    ],
    compatibility: ['Windows', 'macOS', 'Linux', 'Universal'],
    colors: ['Black', 'Silver'],
    reviews: [],
  },
  {
    name: 'Dell OptiPlex 7090 Desktop Computer',
    slug: toSlug('Dell OptiPlex 7090 Desktop Computer'),
    category: 'Computer Equipment',
    brand: 'Dell',
    images: ['/images/p14-1.jpg', '/images/p14-2.jpg'],
    tags: ['new-arrival', 'best-seller', 'todays-deal'],
    isPublished: true,
    price: 899.99,
    listPrice: 1199.99,
    avgRating: 4.5,
    numReviews: 8,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 1 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    numSales: 23,
    countInStock: 7,
    description:
      'Ordinateur de bureau Dell OptiPlex 7090 avec processeur Intel Core i5, 8GB RAM, 256GB SSD et Windows 11 Pro. Idéal pour les entreprises et la bureautique.',
    specifications: ['Intel Core i5', '8GB RAM', '256GB SSD', 'Windows 11 Pro'],
    compatibility: ['Windows 11', 'Universal'],
    colors: ['Black'],
    reviews: [],
  },
  {
    name: 'HP LaserJet Pro M404n Printer',
    slug: toSlug('HP LaserJet Pro M404n Printer'),
    category: 'Computer Equipment',
    brand: 'HP',
    images: ['/images/p15-1.jpg', '/images/p15-2.jpg'],
    tags: ['featured'],
    isPublished: true,
    price: 299.99,
    listPrice: 399.99,
    avgRating: 4.3,
    numReviews: 15,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 1 },
      { rating: 3, count: 2 },
      { rating: 4, count: 5 },
      { rating: 5, count: 6 },
    ],
    numSales: 34,
    countInStock: 9,
    description:
      "Imprimante laser HP LaserJet Pro M404n avec impression monochrome haute qualité, connectivité réseau et impression rapide jusqu'à 40 ppm.",
    specifications: [
      'Monochrome Laser',
      '40 ppm',
      'Network Ready',
      'Duplex Printing',
    ],
    compatibility: ['Windows', 'macOS', 'Linux', 'Universal'],
    colors: ['White'],
    reviews: [],
  },
  {
    name: 'Cisco IP Phone 7841',
    slug: toSlug('Cisco IP Phone 7841'),
    category: 'Telephony',
    brand: 'Cisco',
    images: ['/images/p16-1.jpg', '/images/p16-2.jpg'],
    tags: ['new-arrival', 'featured'],
    isPublished: true,
    price: 89.99,
    listPrice: 129.99,
    avgRating: 4.6,
    numReviews: 11,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 1 },
      { rating: 4, count: 3 },
      { rating: 5, count: 7 },
    ],
    numSales: 18,
    countInStock: 14,
    description:
      'Téléphone IP Cisco 7841 avec écran LCD, support des codecs G.711 et G.729, et compatibilité avec les systèmes de téléphonie IP.',
    specifications: [
      'IP Phone',
      'LCD Display',
      'G.711/G.729 Codecs',
      'PoE Compatible',
    ],
    compatibility: ['Cisco Call Manager', 'Universal SIP'],
    colors: ['Black'],
    reviews: [],
  },
  {
    name: 'Kidde Fire Extinguisher 10-B:C',
    slug: toSlug('Kidde Fire Extinguisher 10-B:C'),
    category: 'Fire',
    brand: 'Kidde',
    images: ['/images/p21-1.jpg', '/images/p21-2.jpg'],
    tags: ['best-seller', 'featured', 'todays-deal'],
    isPublished: true,
    price: 45.99,
    listPrice: 59.99,
    avgRating: 4.8,
    numReviews: 25,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 1 },
      { rating: 4, count: 4 },
      { rating: 5, count: 20 },
    ],
    numSales: 67,
    countInStock: 22,
    description:
      "Extincteur d'incendie Kidde 10-B:C avec agent chimique sec, poignée ergonomique et indicateur de pression. Certifié UL et CSA.",
    specifications: [
      '10-B:C Rating',
      'Dry Chemical',
      'Pressure Gauge',
      'UL/CSA Certified',
    ],
    compatibility: ['Universal'],
    colors: ['Red'],
    reviews: [],
  },
  {
    name: 'First Alert Smoke Detector Battery Powered',
    slug: toSlug('First Alert Smoke Detector Battery Powered'),
    category: 'Fire',
    brand: 'First Alert',
    images: ['/images/p22-1.jpg', '/images/p22-2.jpg'],
    tags: ['new-arrival', 'best-seller'],
    isPublished: true,
    price: 19.99,
    listPrice: 29.99,
    avgRating: 4.4,
    numReviews: 18,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 2 },
      { rating: 4, count: 5 },
      { rating: 5, count: 10 },
    ],
    numSales: 45,
    countInStock: 31,
    description:
      'Détecteur de fumée First Alert alimenté par pile avec technologie photélectrique, bouton de test et alarme de 85 dB.',
    specifications: [
      'Photoelectric Technology',
      '85 dB Alarm',
      'Battery Powered',
      'Test Button',
    ],
    compatibility: ['Universal'],
    colors: ['White'],
    reviews: [],
  },
  {
    name: 'Lenovo ThinkPad X1 Carbon Laptop',
    slug: toSlug('Lenovo ThinkPad X1 Carbon Laptop'),
    category: 'Computer Equipment',
    brand: 'Lenovo',
    images: ['/images/p23-1.jpg', '/images/p23-2.jpg'],
    tags: ['featured', 'premium'],
    isPublished: true,
    price: 1499.99,
    listPrice: 1899.99,
    avgRating: 4.7,
    numReviews: 16,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 1 },
      { rating: 4, count: 3 },
      { rating: 5, count: 12 },
    ],
    numSales: 12,
    countInStock: 5,
    description:
      'Ordinateur portable Lenovo ThinkPad X1 Carbon avec processeur Intel Core i7, 16GB RAM, 512GB SSD et écran 14" 4K. Ultra-léger et ultra-performant.',
    specifications: [
      'Intel Core i7',
      '16GB RAM',
      '512GB SSD',
      '14" 4K Display',
    ],
    compatibility: ['Windows 11', 'Universal'],
    colors: ['Black'],
    reviews: [],
  },
  {
    name: 'Western Digital 2TB Internal Hard Drive',
    slug: toSlug('Western Digital 2TB Internal Hard Drive'),
    category: 'Computer Equipment',
    brand: 'Western Digital',
    images: ['/images/p24-1.jpg', '/images/p24-2.jpg'],
    tags: ['best-seller'],
    isPublished: true,
    price: 59.99,
    listPrice: 79.99,
    avgRating: 4.2,
    numReviews: 22,
    ratingDistribution: [
      { rating: 1, count: 2 },
      { rating: 2, count: 1 },
      { rating: 3, count: 2 },
      { rating: 4, count: 6 },
      { rating: 5, count: 11 },
    ],
    numSales: 89,
    countInStock: 28,
    description:
      'Disque dur interne Western Digital 2TB avec interface SATA 6Gb/s, vitesse de rotation 7200 RPM et technologie IntelliPower.',
    specifications: [
      '2TB Capacity',
      'SATA 6Gb/s',
      '7200 RPM',
      'IntelliPower Technology',
    ],
    compatibility: ['Windows', 'macOS', 'Linux', 'Universal'],
    colors: ['Black'],
    reviews: [],
  },
]
const users: IUserInput[] = [
  {
    name: 'John',
    email: 'admin@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'Admin',
    address: {
      fullName: 'John Doe',
      street: '111 Main St',
      city: 'New York',
      province: 'NY',
      postalCode: '10001',
      country: "Côte d'Ivoire",
      phone: '123-456-7890',
    },
    paymentMethod: 'Stripe',
    emailVerified: false,
  },
  {
    name: 'Jane',
    email: 'jane@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Jane Harris',
      street: '222 Main St',
      city: 'New York',
      province: 'NY',
      postalCode: '1002',
      country: "Côte d'Ivoire",
      phone: '123-456-7890',
    },
    paymentMethod: 'Cash On Delivery',
    emailVerified: false,
  },
  {
    name: 'Jack',
    email: 'jack@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Jack Ryan',
      street: '333 Main St',
      city: 'New York',
      province: 'NY',
      postalCode: '1003',
      country: "Côte d'Ivoire",
      phone: '123-456-7890',
    },
    paymentMethod: 'PayPal',
    emailVerified: false,
  },
  {
    name: 'Sarah',
    email: 'sarah@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Sarah Smith',
      street: '444 Main St',
      city: 'New York',
      province: 'NY',
      postalCode: '1005',
      country: "Côte d'Ivoire",
      phone: '123-456-7890',
    },
    paymentMethod: 'Cash On Delivery',
    emailVerified: false,
  },
  {
    name: 'Michael',
    email: 'michael@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'John Alexander',
      street: '555 Main St',
      city: 'New York',
      province: 'NY',
      postalCode: '1006',
      country: "Côte d'Ivoire",
      phone: '123-456-7890',
    },
    paymentMethod: 'PayPal',
    emailVerified: false,
  },
  {
    name: 'Emily',
    email: 'emily@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Emily Johnson',
      street: '666 Main St',
      city: 'New York',
      province: 'NY',
      postalCode: '10001',
      country: "Côte d'Ivoire",
      phone: '123-456-7890',
    },
    paymentMethod: 'Stripe',
    emailVerified: false,
  },
  {
    name: 'Alice',
    email: 'alice@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Alice Cooper',
      street: '777 Main St',
      city: 'New York',
      province: 'NY',
      postalCode: '10007',
      country: "Côte d'Ivoire",
      phone: '123-456-7890',
    },
    paymentMethod: 'Cash On Delivery',
    emailVerified: false,
  },
  {
    name: 'Tom',
    email: 'tom@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Tom Hanks',
      street: '888 Main St',
      city: 'New York',
      province: 'NY',
      postalCode: '10008',
      country: "Côte d'Ivoire",
      phone: '123-456-7890',
    },
    paymentMethod: 'Stripe',
    emailVerified: false,
  },
  {
    name: 'Linda',
    email: 'linda@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Linda Holmes',
      street: '999 Main St',
      city: 'New York',
      province: 'NY',
      postalCode: '10009',
      country: "Côte d'Ivoire",
      phone: '123-456-7890',
    },
    paymentMethod: 'PayPal',
    emailVerified: false,
  },
  {
    name: 'George',
    email: 'george@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'George Smith',
      street: '101 First Ave',
      city: 'New York',
      province: 'NY',
      postalCode: '10010',
      country: "Côte d'Ivoire",
      phone: '123-456-7890',
    },
    paymentMethod: 'Stripe',
    emailVerified: false,
  },
  {
    name: 'Jessica',
    email: 'jessica@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Jessica Brown',
      street: '102 First Ave',
      city: 'New York',
      province: 'NY',
      postalCode: '10011',
      country: "Côte d'Ivoire",
      phone: '123-456-7890',
    },
    paymentMethod: 'Cash On Delivery',
    emailVerified: false,
  },
  {
    name: 'Chris',
    email: 'chris@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Chris Evans',
      street: '103 First Ave',
      city: 'New York',
      province: 'NY',
      postalCode: '10012',
      country: "Côte d'Ivoire",
      phone: '123-456-7890',
    },
    paymentMethod: 'PayPal',
    emailVerified: false,
  },
  {
    name: 'Samantha',
    email: 'samantha@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Samantha Wilson',
      street: '104 First Ave',
      city: 'New York',
      province: 'NY',
      postalCode: '10013',
      country: "Côte d'Ivoire",
      phone: '123-456-7890',
    },
    paymentMethod: 'Stripe',
    emailVerified: false,
  },
  {
    name: 'David',
    email: 'david@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'David Lee',
      street: '105 First Ave',
      city: 'New York',
      province: 'NY',
      postalCode: '10014',
      country: "Côte d'Ivoire",
      phone: '123-456-7890',
    },
    paymentMethod: 'Cash On Delivery',
    emailVerified: false,
  },
  {
    name: 'Anna',
    email: 'anna@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Anna Smith',
      street: '106 First Ave',
      city: 'New York',
      province: 'NY',
      postalCode: '10015',
      country: "Côte d'Ivoire",
      phone: '123-456-7890',
    },
    paymentMethod: 'PayPal',
    emailVerified: false,
  },
]

const data: Data = {
  users,
  headerMenus: [
    {
      name: "Today's Deal",
      href: '/search?tag=todays-deal',
    },
    {
      name: 'New Arrivals',
      href: '/search?tag=new-arrival',
    },
    {
      name: 'Featured Products',
      href: '/search?tag=featured',
    },
    {
      name: 'Best Sellers',
      href: '/search?tag=best-seller',
    },
    {
      name: 'Browsing History',
      href: '/#browsing-history',
    },
    {
      name: 'Customer Service',
      href: '/page/customer-service',
    },
    {
      name: 'About Us',
      href: '/page/about-us',
    },
    {
      name: 'Help',
      href: '/page/help',
    },
  ],
  carousels: [
    {
      title: 'Most Popular Computer Equipment For Sale',
      buttonCaption: 'Shop Now',
      image: '/images/banner3.jpg',
      url: '/search?category=Computer Equipment',
      isPublished: true,
    },
    {
      title: 'Best Sellers in Telephony',
      buttonCaption: 'Shop Now',
      image: '/images/banner1.jpg',
      url: '/search?category=Telephony',
      isPublished: true,
    },
    {
      title: 'Best Deals on Video Surveillance',
      buttonCaption: 'See More',
      image: '/images/banner2.jpg',
      url: '/search?category=Video Surveillance',
      isPublished: true,
    },
  ],
  products,
}

export default data
